--This script will create the tables in accordance with the schema

USE cis560_team10;

DROP TABLE IF EXISTS MovieDB.MoviePerson;
DROP TABLE IF EXISTS MovieDB.MovieGenre;
DROP TABLE IF EXISTS MovieDB.[Role];
DROP TABLE IF EXISTS MovieDB.Person;
DROP TABLE IF EXISTS MovieDB.Movie;
DROP TABLE IF EXISTS MovieDB.Genre;


CREATE TABLE MovieDB.Movie
(
	MovieID NVARCHAR(32) NOT NULL PRIMARY KEY,
	Title NVARCHAR(128) NOT NULL,
	Runtime INT NOT NULL,
	YearReleased INT NOT NULL,
	UNIQUE(Title, YearReleased, Runtime)
);

CREATE TABLE MovieDB.Genre
(
	GenreID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(32) NOT NULL,
	UNIQUE(Name)
);

CREATE TABLE MovieDB.[Role]
(
	RoleID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(64) NOT NULL,
	UNIQUE(Name)
);

CREATE TABLE MovieDB.Person
(
	PersonID NVARCHAR(32) NOT NULL PRIMARY KEY,
	FirstName NVARCHAR(32) NOT NULL,
	LastName NVARCHAR(32) NOT NULL,
	UpdateOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
	UNIQUE(FirstName, LastName)
);

CREATE TABLE MovieDB.MovieGenre
(
	MovieGenreID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	MovieID NVARCHAR(32) NOT NULL FOREIGN KEY
		REFERENCES MovieDB.Movie(MovieID),
	GenreID INT NOT NULL FOREIGN KEY
		REFERENCES MovieDB.Genre(GenreID),
	UpdatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
	UNIQUE(MovieID, GenreID)
);

CREATE TABLE MovieDB.MoviePerson
(
	MoviePersonID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	MovieID NVARCHAR(32) NOT NULL FOREIGN KEY	
		REFERENCES MovieDB.Movie(MovieID),
	PersonID NVARCHAR(32) NOT NULL FOREIGN KEY
		REFERENCES MovieDB.Person(PersonID),
	RoleID INT NOT NULL FOREIGN KEY
		REFERENCES MovieDB.[Role](RoleID),
	CharacterName NVARCHAR(64),
	UNIQUE(MovieID, PersonID, RoleID)
);



